name: Deploy to EC2

on:
  push:
    branches: [ "feature/USS31002_SN" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy_via_ssh:
    
    runs-on: ubuntu-22.04
    
    steps:
      
      
      - run: pwd;ls
      
      - run: cp -r ./docker-compose.yml ./
      - run: ls 
      
      - name: copy files to target server via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          port: 22
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./docker-compose.yml"
          target: "./user"
      
      
           
      # Deploy Docker image with your application using `docker compose up app` remotely
      - name: remote docker-compose up via ssh
        uses: appleboy/ssh-action@v0.1.5
        env:
          
          USERNAME: ${{ secrets.DEPLOY_USERNAME }}
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          
          script: |
            pwd;ls
            docker compose up -d
            
