name: Deploying Services

on:
  push:
    branches: [ "feature/USS31002_SN" ]
  pull_request:
    branches: [ "master" ]

jobs:
 
        
         
  deploy:
    name: Deploy to EC2
    runs-on: self-hosted
    
    
    steps:
         - run: pwd ; cd PPS_SERVICES/. ; docker compose up -d &
         